//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDocumentDB.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://abedcumentdb.documents.azure.com:443/")]
        public string EndpointUri {
            get {
                return ((string)(this["EndpointUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jLPii2cqAKrYwel4H4EKHIjc7SOFwZpn1CntZWyo5B3Gq9CsOZb8ikxgU2GfYVYvlBkZmZ7gugXaI0Wk2" +
            "Q9wsQ==")]
        public string PrimaryKey {
            get {
                return ((string)(this["PrimaryKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AccountEndpoint=https://abedcumentdb.documents.azure.com:443/;AccountKey=jLPii2cq" +
            "AKrYwel4H4EKHIjc7SOFwZpn1CntZWyo5B3Gq9CsOZb8ikxgU2GfYVYvlBkZmZ7gugXaI0Wk2Q9wsQ==" +
            ";")]
        public string PrimaryConnectionString {
            get {
                return ((string)(this["PrimaryConnectionString"]));
            }
        }
    }
}
