//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureStorageBlob.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=abestorageaccount;AccountKey=l+2HHunyv" +
            "uOOFnnJX9/C2j6CD/70+Hsbuj4mAnWZVJDXJv9j0SMUIyfSBlHF0N995i8PiTMZUdSKoAiYnRkWTg==")]
        public string StorageConnectionString {
            get {
                return ((string)(this["StorageConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://abestorageaccount.blob.core.windows.net/sheardaccesssignature/MyBlob.txt")]
        public string SASUri {
            get {
                return ((string)(this["SASUri"]));
            }
            set {
                this["SASUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?sv=2015-12-11&si=mypolicy&sr=c&sig=0w4c1UdFL%2FvPLd03%2Fyhnfiv3THAY2YwEFaD4kcGKD" +
            "3w%3D")]
        public string SASToken {
            get {
                return ((string)(this["SASToken"]));
            }
            set {
                this["SASToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://abestorageaccount.blob.core.windows.net/sheardaccesssignatureip/MyBlobIP." +
            "txt")]
        public string SASIPUri {
            get {
                return ((string)(this["SASIPUri"]));
            }
            set {
                this["SASIPUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?sv=2015-12-11&si=mypolicyip3&sr=c&sig=zWhpQ9yH%2Fs8hV0bqFcyrxwlYCvuT8KHRHcvIJ9%2" +
            "FSGgg%3D")]
        public string SASIPToken {
            get {
                return ((string)(this["SASIPToken"]));
            }
            set {
                this["SASIPToken"] = value;
            }
        }
    }
}
