//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bearer {payjZQCNhfBreBxIpqXhao0dfh5Htg / aHbky3W7pp10NedytEPeLuwxeMnjJK3rJvbloP1O" +
            "rxl7vLlPcsuqQBa8ZATqcvw4ml5LwWuEEnQ78sTSpozq959ua7oAAWyTN15fGialEMdT0619gu4NIZQd" +
            "B04t89 / 1O/w1cDnyilFU=}")]
        public string Authorization {
            get {
                return ((string)(this["Authorization"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c1f72b92935047a4a8c8a8765a68124c")]
        public string SubscriptionKey {
            get {
                return ((string)(this["SubscriptionKey"]));
            }
        }
    }
}
